import './globals.css'
import type { Metadata } from 'next'
import { Libre_Bodoni } from 'next/font/google'
import Footer from './components/Footer'
import Nav from "./components/Nav"


const roboto = Libre_Bodoni({  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'A Plus Studio',
  description: 'Generated by Gulfaam',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={roboto.className}>
        <Nav />
        {children}
      <Footer/>
      </body>
    </html>
  )
}
