import './globals.css'
import './not-found'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'
import Nav from "./components/Nav"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'A Plus Studio',
  description: 'Generated by Gulfaam',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{fontFamily:'inherit'}} className={inter.className}>
        <Nav />
        {children}
      <Footer/>
      </body>
    </html>
  )
}
